### ISSUE TITLE
Redis issue

### ISSUE THREAD

**Issue by egarciadev** [iGLOO-be/cron-cluster#2]
Hi: @Natsuke 

I'm using latest redis version, when pass redis client to cron-cluster I got this

Err wrong number of arguments for set command.

This my code

var client = require("redis").createClient();
var CronJob = require('cron-cluster')(client).CronJob

  var job = new CronJob('\* \* \* \* \* *', function () {
    console.log("here timer");
  })
  job.start()

May someone help me with that. tks

**Comment by LoicMahieu** [comment]
Hi @egarciadev 

Which version of redis ?
Tried with redis@2.4.2 without problem. Can you paste the outpout/error ?

**Comment by egarciadev** [comment]
Hi tks for your answer my redis version is 2.4.6 for windows.
this is the ouput:
![issue](https://cloud.githubusercontent.com/assets/10061425/12817090/3c1d826c-cb1e-11e5-84b2-39798c407b0e.PNG)

**Comment by LoicMahieu** [comment]
Ok I presume you talk about your server version ?
I never tested this module on Windows.
Did you tried a simpler app without socket.io ?

**Comment by egarciadev** [comment]
Yes, I have tested but not success, and yes this is my server version running on windows 7

**Comment by LoicMahieu** [comment]
Ok. Sorry but without more information I can do more :) Do you have a complete sample ? More information about versions etc...
- `npm ls`
- `node --version`
- `redis-server --version`
- .......

**Comment by egarciadev** [comment]
allrigth:
node 0.12.4
redis-server 2.4.6
[npm.txt](https://github.com/iGLOO-be/cron-cluster/files/117602/npm.txt)

tks very much

**Comment by LoicMahieu** [comment]
Please try to simplify the problem, I see lot of other dependencies in your project.

**Comment by egarciadev** [comment]
Ok, the npm.text has been updated, only express, socket and cron are left, hope it's helpful

**Comment by LoicMahieu** [comment]
Nop. Please try the sample you posted above. Without express/socket etc.... What's append ?

**Comment by egarciadev** [comment]
ok, let me ask for it tks

**Comment by egarciadev** [comment]
Same error, I have tried without socket, express etc just with the first example posted here:
![issue](https://cloud.githubusercontent.com/assets/10061425/12818927/da73a574-cb26-11e5-97bd-3598b4f9f530.PNG)

the node version and redis version are the same:

├── cron-cluster@1.0.0 
├── redis@2.4.2

**Comment by egarciadev** [comment]
Same error, I have tried with the simple example I posted before, this time without socket or  express just cron-cluster and redis:

![issue](https://cloud.githubusercontent.com/assets/10061425/12819076/8f8b2aae-cb27-11e5-9633-291b54b504c3.PNG)

├── cron-cluster@1.0.0 
├── redis@2.4.2

**Comment by LoicMahieu** [comment]
Mmh... Sorry I don't know what happens. I suggest you look at `redis-leader` which is the module that send request to redis: https://github.com/pierreinglebert/redis-leader
I see a requirement: Redis-server 2.6.12
