### ISSUE TITLE
Remove deprecated lodash.wrap dependency

### ISSUE THREAD

**Issue by skeggse** [iGLOO-be/cron-cluster#6]
Per https://github.com/lodash/lodash/issues/3744#issuecomment-409127068, the modularized `lodash` packages are deprecated. Let's use `lodash/wrap` instead of `lodash.wrap`!

**Comment by LoicMahieu** [comment]
Hi @skeggse 
Indeed I don't use theses packages. We don't actively support this package but if you have time, open a merge request. Thanks!
